import { Topic } from '@/types/curriculum';

export const TOPICS: Topic[] = [
  {
    id: 'what-is-coding',
    number: '01',
    title: 'Apa Itu Coding?',
    subtitle: 'Pengenalan Dunia Coding',
    description: 'Pahami apa itu coding, bagaimana komputer bekerja, dan mengapa instruksi harus jelas dan berurutan.',
    icon: 'code-icon',
    type: 'quiz_topic',
    sections: [
      {
        id: 'sec-1',
        title: 'Apa itu Coding?',
        content: 'Coding adalah cara kita berkomunikasi dan memberikan instruksi kepada komputer menggunakan bahasa yang dimengerti oleh komputer.',
        illustrationType: 'diagram',
      },
      {
        id: 'sec-2',
        title: 'Komputer Membutuhkan Instruksi',
        content: 'Komputer adalah mesin yang sangat cepat, tetapi membutuhkan panduan yang sangat spesifik dan urut untuk melakukan pekerjaan.',
        illustrationType: 'none',
      },
      {
        id: 'sec-3',
        title: 'Coding Ada di Sekitar Kita',
        content: 'Game favoritmu, aplikasi di ponsel orang tuamu, hingga robot pembersih rumah semuanya menggunakan kode!',
        illustrationType: 'comparison',
      },
      {
        id: 'sec-4',
        title: 'Coding Harus Jelas dan Berurutan',
        content: 'Jika kamu memberikan instruksi yang salah atau terbalik, komputer akan bingung dan hasilnya tidak sesuai.',
        illustrationType: 'diagram',
      },
      {
        id: 'sec-5',
        title: 'Bahasa Pemrograman',
        content: 'Ada banyak bahasa coding: HTML untuk membuat rangka website, CSS untuk menghias tampilan, dan JavaScript untuk memberi aksi.',
        illustrationType: 'comparison',
      },
    ],
    quizQuestions: [
      {
        id: 'q1',
        question: 'Apa yang dimaksud dengan coding?',
        options: [
          'Cara menggambar di komputer',
          'Cara memberikan instruksi kepada komputer',
          'Cara bermain game online',
          'Cara memperbaiki komputer rusak',
        ],
        correctAnswerIndex: 1,
        explanation: 'Coding adalah proses memberikan instruksi langkah demi langkah agar komputer tahu apa yang harus dilakukan.',
      },
      {
        id: 'q2',
        question: 'Mengapa instruksi coding harus jelas dan berurutan?',
        options: [
          'Agar komputer tidak bingung dan dapat menjalankan tugas dengan benar',
          'Agar komputer bekerja lebih lambat',
          'Agar kode terlihat indah',
          'Agar aplikasi menjadi lebih mahal',
        ],
        correctAnswerIndex: 0,
        explanation: 'Komputer mengikuti perintah tepat sesuai urutan. Jika urutannya salah, hasilnya akan salah.',
      },
      {
        id: 'q3',
        question: 'Bahasa apa yang digunakan untuk mengatur tampilan dan warna website?',
        options: ['HTML', 'CSS', 'JavaScript', 'Python'],
        correctAnswerIndex: 1,
        explanation: 'CSS (Cascading Style Sheets) bertugas memberi warna, gaya, dan mempercantik tampilan website.',
      },
      {
        id: 'q4',
        question: 'Mana di bawah ini yang merupakan contoh hasil dari coding?',
        options: [
          'Game komputer & aplikasi handphone',
          'Buku tulis & pensil',
          'Kertas bergambar',
          'Meja belajar',
        ],
        correctAnswerIndex: 0,
        explanation: 'Game dan aplikasi seluler dibuat oleh programmer menggunakan kode pemograman.',
      },
      {
        id: 'q5',
        question: 'Apa peran JavaScript dalam pembuatan website?',
        options: [
          'Membuat struktur dasar tulisan',
          'Memberikan warna background',
          'Memberikan aksi interaktif saat tombol diklik',
          'Mencetak halaman ke kertas',
        ],
        correctAnswerIndex: 2,
        explanation: 'JavaScript bertugas menangani interaksi, seperti aksi saat tombol diklik atau animasi bergerak.',
      },
    ],
  },
  {
    id: 'algorithm',
    number: '02',
    title: 'Algorithm',
    subtitle: 'Langkah Demi Langkah',
    description: 'Pelajari konsep algoritma, pentingnya urutan langkah (sequence), dan cara berpikir logis.',
    icon: 'algorithm-icon',
    type: 'quiz_topic',
    sections: [
      {
        id: 'sec-1',
        title: 'Apa itu Algoritma?',
        content: 'Algoritma adalah urutan langkah-langkah logis untuk menyelesaikan suatu masalah atau pekerjaan.',
        illustrationType: 'diagram',
      },
    ],
  },
  {
    id: 'html',
    number: '03',
    title: 'HTML Basics',
    subtitle: 'Rangka Website',
    description: 'Pelajari elemen dasar HTML untuk membuat judul, paragraf, dan tombol website.',
    icon: 'html-icon',
    type: 'coding_topic',
    sections: [],
  },
  {
    id: 'css',
    number: '04',
    title: 'CSS Basics',
    subtitle: 'Menghias Website',
    description: 'Ubah warna, ukuran teks, dan gaya elemen website dengan CSS.',
    icon: 'css-icon',
    type: 'coding_topic',
    sections: [],
  },
  {
    id: 'javascript',
    number: '05',
    title: 'JavaScript Basics',
    subtitle: 'Interaksi & Aksi',
    description: 'Pelajari cara membuat tombol berinteraksi dan membuat website terasa hidup.',
    icon: 'js-icon',
    type: 'coding_topic',
    sections: [],
  },
  {
    id: 'final-project',
    number: '06',
    title: 'Final Project',
    subtitle: 'Buat Website Pertamamu',
    description: 'Gabungkan HTML, CSS, dan JavaScript untuk membuat proyek website pribadi dan raih sertifikatmu!',
    icon: 'project-icon',
    type: 'project_topic',
    sections: [],
  },
];
